services:
  - type: web
    name: gestor-turnos-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./www
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
